plugins {
    id 'org.springframework.boot'
}

description = 'application'

dependencies {
    implementation project(':movie-api')
    implementation project(':movie-core')
    implementation project(':movie-kafka')
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb-reactive'
    implementation 'org.springframework.boot:spring-boot-starter-json'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

springBoot {
    mainClass = 'com.ecommerce.application.Application'
}