plugins {
	id 'java'
}

group = 'com.ecommerce'
version = '0.0.1-SNAPSHOT'
description = 'movie-core'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation project(':movie-kafka')
	implementation 'org.springframework.boot:spring-boot-starter-data-mongodb-reactive'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation "org.mapstruct:mapstruct:$mapstruct_version"
	annotationProcessor "org.mapstruct:mapstruct-processor:$mapstruct_version"
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
