spring:

  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 10s
    socket-timeout: 10s


  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://admin:admin@localhost:27017/moviehub?authSource=admin&serverSelectionTimeoutMS=1000000000&socketTimeoutMS=2000000000

    elasticsearch:
      repositories:
        enabled: true


  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: movie-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"

logging:
  file:
    name: logs/app.log