input {
  file {
    path => "/usr/share/logstash/logs/*.log"
    codec => json
    type => "logback"
  }
}


output {
  if [type] == "logback" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "spring-logs-%{+YYYY.MM.dd}"
    }
  }
}