plugins {
    id 'java'
}

group = 'com.ecommerce'
version = '0.0.1-SNAPSHOT'
description = 'movie-api'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':movie-core')
    implementation project(':movie-elastic')
    implementation project(':movie-kafka')
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
